apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxnoa
  name: nginxnoa
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: accelerator
            operator: In
            values:
            - nvidia-tesla-p100
  containers:
  - image: nginx
    name: nginxnoa
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
