apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox2
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox
    volumeMounts:
      - mountPath: "/etc/foo"
        name: mypd
    resources: {}
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: mypvc
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
