kind: Pod
apiVersion: v1
metadata: 
  name: devpod
  labels: 
    app: web
spec: 
  volumes: 
    - name: sec-vol
      secret:
         secretName: mysec
  containers: 
    - name: cont1
      image: tomcat
      ports: 
        - containerPort: 8080
      volumeMounts:
         - name: sec-vol
           mountPath: /etc/sec-data


--- 

kind: Pod
apiVersion: v1
metadata:
  name: prodpod
  labels:
    app: myapp
spec:
  containers:
    - name: cont1
      image: tomcat
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: mysec

---

kind: Pod
apiVersion: v1
metadata:
  name: mypod
  labels:
    app: myapp
spec:
  containers:
    - name: cont1
      image: tomcat
      ports:
        - containerPort: 8080
      env: 
        - name: dbuser
          valueFrom:
            secretKeyRef:
               name: mysec
               key: username
        - name: dbpwd
          valueFrom:
            secretKeyRef:
               name: mysec
               key: password
        - name: myname
          value: naresh
        - name: DCA
          value: trainer
