kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: practice-nginx # pick a name
spec:
  podSelector:
    matchLabels:
      app: nginx-ing # selector for the pods
  ingress: # allow ingress traffic
  - from:
    - podSelector: # from pods
        matchLabels: # with this label
          access: granted
