apiVersion: v1
kind: Pod
metadata:
  name: memory
spec:
  containers:
  - name: memory-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "200Gi"
      requests:
        memory: "100Gi"
