apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: adng
  name: adng
spec:
  containers:
  - image: nginx
    name: adng
    resources: {}
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
