apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ngpvc
  name: ngpvc
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
  - image: nginx
    name: ngpvc
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
