apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ngn1
  name: ngn1
spec:
  nodeSelector:
    nodeName: ngincnode
  containers:
  - image: nginx
    name: ngn1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
